services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        expose:
            - "9000"
        volumes:
            - ./:/var/www/html:cached
            - app_storage:/var/www/html/storage
            - app_bootstrap_cache:/var/www/html/bootstrap/cache
        environment:
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST:       ${DB_HOST}
            DB_PORT:       ${DB_PORT}
            DB_DATABASE:   ${DB_DATABASE}
            DB_USERNAME:   ${DB_USERNAME}
            DB_PASSWORD:   ${DB_PASSWORD}
        networks:
            - laravel_net
        depends_on:
            pgsql:
                condition: service_healthy

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./:/var/www/html:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - laravel_net

    pgsql:
        image: postgis/postgis:15-3.3
        container_name: pgsql
        environment:
            POSTGRES_DB:       ${DB_DATABASE}
            POSTGRES_USER:     ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge

volumes:
    pgdata:
    app_storage:
    app_bootstrap_cache:
