services:
  app:
    image: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www/html
    networks:
      - laravel_net
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/sites-available/default
        - ./app:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - app

  pgsql:
    image: postgres:15
    container_name: pgsql
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  pgdata:
